import { CopyCatalog } from './copy.types';

export const copy: CopyCatalog = {
  metadata: {
    titleDefault: 'Decantd - Personalized Wine Tasting Plans',
    titleTemplate: '%s | Decantd',
    description:
      'Build clear, sommelier-guided wine tasting plans with food pairing logic, tasting order, and practical notes you can actually use at the table.',
    manifestName: 'Decantd - Wine Tasting Plans',
    manifestDescription:
      'Create practical wine tasting plans with pairing guidance, flavor structure, and a clear pour order.',
  },
  landing: {
    badge: 'Decantd Tasting Planner',
    title: 'Plan a Better Wine Night',
    subtitle:
      'Tell us what you are serving, who is coming, and how you want the night to feel. We build a clear lineup from light to bold.',
    cta: 'Start Your Plan',
    stepsTitle: 'How It Works',
    steps: [
      {
        step: '1',
        title: 'Set context',
        description: 'Share your occasion, food, and preferences in under a minute.',
      },
      {
        step: '2',
        title: 'Review your lineup',
        description: 'Get bottle recommendations with order, pairings, and tasting notes.',
      },
      {
        step: '3',
        title: 'Taste with confidence',
        description: 'Open your plan, pour in sequence, and save what worked for next time.',
      },
    ],
  },
  auth: {
    signupTitle: 'Create Your Account',
    loginTitle: 'Welcome Back',
    signupDescription:
      'Save plans, rate wines, and build a palate profile that improves your recommendations over time.',
    loginDescription: 'Sign in to access your journal, saved plans, and guided tasting history.',
    googleIdle: 'Continue with Google',
    googleLoading: 'Opening Google sign-in...',
    signupCta: 'Create Account',
    loginCta: 'Sign In',
    signupSwitchPrompt: 'Already have an account?',
    loginSwitchPrompt: "Don't have an account?",
    signupSwitchCta: 'Sign in',
    loginSwitchCta: 'Create one',
    forgotTitle: 'Reset Your Password',
    forgotDescription: "Enter your email and we'll send a reset link.",
    forgotSentTitle: 'Check Your Email',
    forgotSentDescription:
      "If an account exists for that email, we've sent a password reset link. Check your inbox and spam folder.",
    forgotSubmitCta: 'Send Reset Link',
    backToSignIn: 'Back to sign in',
    placeholders: {
      email: 'you@example.com',
      displayName: 'Your name',
      signupPassword: '8+ characters',
      loginPassword: 'Your password',
    },
    welcomeSignupToast: 'Account created. Welcome to Decantd.',
    welcomeLoginToast: 'Signed in successfully.',
  },
  generation: {
    title: 'Building Your Tasting Plan',
    subtitle: 'We are selecting wines, ordering the pour, and drafting pairing notes.',
    idleTitle: 'No active plan generation',
    idleDescription: 'Start a new tasting plan and we will show live progress here.',
    idleCta: 'Start a new plan',
    readyTitle: 'Your tasting plan is ready',
    readyDescription: 'Open your lineup and start with the first pour.',
    readyCta: 'Open plan',
    actions: [
      { verb: 'Reviewing your context', detail: 'Checking occasion, budget, and preferences.' },
      { verb: 'Selecting candidate wines', detail: 'Filtering for fit, value, and style match.' },
      { verb: 'Balancing the lineup', detail: 'Aligning acidity, body, and tannin progression.' },
      { verb: 'Setting tasting order', detail: 'Arranging pours from lighter to fuller styles.' },
      { verb: 'Drafting pairing notes', detail: 'Writing clear, practical food matches.' },
      { verb: 'Final quality check', detail: 'Ensuring the plan reads clearly and holds together.' },
    ],
  },
  toasts: {
    generationLoading: 'Building your tasting plan...',
    generationErrorFallback: 'We could not generate your tasting plan. Please try again.',
    generationReady: 'Your tasting plan is ready.',
    generationReturnAction: 'View progress',
    generationOpenAction: 'Open plan',
    shareCopied: 'Link copied.',
    imageSaved: 'Image saved.',
    imageSaveFailed: 'Could not save image.',
    emailSent: 'Email sent.',
    emailFailed: 'Could not send email.',
    palateCopied: 'Palate profile copied to clipboard.',
    ratingSaved: 'Rating saved.',
    ratingFailed: 'Could not save rating.',
  },
  home: {
    subtitle: 'Pick your occasion, build a lineup, and track what you loved.',
    createPlan: 'Create New Tasting Plan',
    palateTitle: 'My Palate',
    recentPlansTitle: 'Recent Plans',
    viewAll: 'View all',
    journalCta: 'Open tasting journal',
  },
  review: {
    title: 'Review Your Plan Inputs',
    subtitle: 'Confirm the details below, then generate your recommendations.',
    optionalNoteLabel: 'Optional note for your sommelier',
    optionalNotePlaceholder: 'Example: prioritize crowd-pleasing pairings and one low-prep option.',
    optionalNoteLockedPlaceholder: 'Upgrade to add a custom note for generation.',
    optionalNoteUpgradeHint: 'Upgrade to add custom generation instructions.',
    upgradeInlineMessage: 'Unlock custom sommelier notes and advanced refinements.',
    upgradeRateLimitMessage: "You've reached today's limit. Upgrade for unlimited plans or try again tomorrow.",
    upgradeAnonymousMessage: 'Create an account for personalized plans and higher daily limits.',
    backCta: 'Back',
    generateLoading: 'Generating plan...',
    generateFoodToWine: 'Generate Plan',
    generateWineToFood: 'Generate Pairings',
    modeFoodToWine: 'Food to Wine',
    modeWineToFood: 'Wine to Food',
    notSpecified: 'Not specified',
    surprise: 'Surprise me',
    openCuisine: 'Open',
    remainingTodaySuffix: 'tastings remaining today',
  },
  explore: {
    title: 'Explore Wine Skills',
    subtitle: 'Use practical tools to build confidence in tasting, aroma recognition, and service.',
    newPlanTitle: 'Build a New Tasting Plan',
    newPlanDescription: 'Turn your menu and occasion into a structured lineup with clear rationale.',
    features: {
      guided: {
        title: 'Guided Tasting',
        description: 'Follow Look -> Smell -> Taste -> Think with clear prompts and structure.',
        badge: 'Interactive',
      },
      aroma: {
        title: 'Aroma Wheel',
        description: 'Practice identifying aroma families from broad categories to specific notes.',
        badge: 'Interactive',
      },
      serving: {
        title: 'Serving Guide',
        description: 'Get quick reference on serving temperature, glassware, and decanting.',
        badge: 'Reference',
      },
      corkage: {
        title: 'Corkage Directory',
        description: 'Find BYOB-friendly restaurants and check current corkage policies.',
        badge: 'Toronto',
      },
    },
  },
  plan: {
    backToJournal: 'Back to Journal',
    summaryFoodToWine:
      'Follow the sequence below and use the notes to understand why each wine works.',
    summaryWineToFood:
      'Start with the top dish options, then use host notes to execute smoothly.',
    corkageTitle: 'Bringing wine to dinner?',
    corkageDescription: 'Find nearby corkage-friendly restaurants.',
    flexibleCuisine: 'Flexible cuisine',
    deepDiveTitle: 'Sommelier Notes',
    estimatedTotalPrefix: 'Estimated total',
    selectedWinePrefix: 'Selected wine',
    pairingDirectionPrefix: 'Pairing direction',
    saveTitle: 'Save this plan to your collection',
    saveDescription: 'Create an account to track tastings, rate wines, and build your palate profile.',
    saveCta: 'Create Free Account',
    createAnotherCta: 'Create Another Plan',
    pairingsCountLabel: 'pairings',
    winesSingular: 'wine',
    winesPlural: 'wines',
  },
  profile: {
    plansLoadError: 'Unable to load your plans.',
    noPlansTitle: 'No plans yet',
    noPlansDescription: 'Create your first tasting plan to see it here.',
    profileTitle: 'Your Palate Profile',
    profileUnlockFallback: 'Rate at least 3 wines to unlock your palate profile.',
    profileShareTitle: 'My Wine Palate',
    topRegions: 'Top Regions',
    topVarietals: 'Top Varietals',
    adventurousness: 'Adventurousness',
    basedOnRatingsPrefix: 'Based on',
  },
};
